### ISSUE TITLE
Verify provisioned clusters pass the EKS CIS benchmark

### ISSUE THREAD

**Issue by mogul** [GSA/datagov-brokerpak-eks#6]
## User Story

In order to give auditors confidence that provisioned EKS clusters are following best-practices, we should be able to demonstrate that a provisioned cluster can pass [the CIS EKS benchmark](https://aws.amazon.com/it/blogs/containers/introducing-cis-amazon-eks-benchmark/).

## Acceptance Criteria
- [x] GIVEN I have installed the `tree` kubectl plugin \
  WHEN I use `kubectl tree` on pods and nodes \
  THEN I see resources that containing scanning results are present
- [x] WHEN I run `kubectl get CISKubeBenchReport <nodename> -o wide` \
  THEN I see a report indicating no tests failed
- [x] WHEN I run `kubectl get CISKubeBenchReport <nodename> -o yaml` \
  THEN I see a detailed report
- [x] WHEN I run `make clean build up demo-up demo-test` \
  THEN I see that there is a test for a CISKubeBenchReport with zero FAIL results

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

See also this [GSA ISE hardening guide for EKS](https://insite.gsa.gov/cdnstatic/insite/AWS_Elastic_Kubernetes_Service_Hardening_[CIO-IT_Security_21-110_Initial_Release]_11-20-2020docx.pdf)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
This change will ensure that any new deployment of the eks-brokerpak will only deploy CIS-compliant instances of AWS EKS. This will bolster confidence in the configuration of the EKS instances we create.

## Sketch

1. Install the Aquasec `starboard-operator`
1. Add lines at [the end of the tests](https://github.com/GSA/datagov-brokerpak-eks/blob/main/test.sh) that check that the AWS EKS CIS benchmark had zero FAIL results
1. Document how someone can check these reports on any existing instance

Note that [AWS Security Hub](https://aws.amazon.com/about-aws/whats-new/2020/12/aws-security-hub-adds-open-source-tool-integration-with-kube-bench-and-cloud-custodian/) can ingest kube-bench results. We may want to set this up if it turns out that we need to continuously report on existing instances, but it's probably out of scope for this story. Let's wait to see if it's required, and write that separate story when it's time.

**Comment by mogul** [comment]
I just noticed [this](https://aws.amazon.com/blogs/containers/introducing-cis-amazon-eks-benchmark/):
> The EKS Benchmark is applicable to EC2 nodes (both managed and self managed) where you’re responsible for security configurations of Kubernetes components. This benchmark is, however, not applicable to Amazon EKS on AWS Fargate as you do not own or manage Kubernetes component configurations when using AWS Fargate. 

Since the control plane is AWS' responsibility and we run no nodes, I guess there's no value in running the benchmark for us and we don't need to do this story...?

**Comment by mogul** [comment]
Here's [a nice blog post on how to run the CISbenchmark from within the cluster](https://scalefactory.com/blog/2021/03/31/assess-eks-security-with-kube-bench/); it provides a ready-to-go manifest and instructions for getting the results.

**Comment by mogul** [comment]
`kube-bench` doesn't even run in Fargate, at least without further tweaking:
```
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2021-04-28T00:28:26Z"
      message: 'Pod not supported on Fargate: fields not supported: HostPID, volumes
        not supported: var-lib-kubelet is of an unsupported volume Type, etc-systemd
        is of an unsupported volume Type, etc-kubernetes is of an unsupported volume
        Type'
      reason: POD_UNSUPPORTED_ON_FARGATE
      status: "False"
      type: PodScheduled
    phase: Pending
    qosClass: BestEffort
```

I'll do some further digging, but I'm increasingly thinking that the CIS benchmark doesn't apply to us...
